---
title: "kommune"
author: "Astrid Elmann Hansen"
date: '2023-08-05'
output: html_document
---

This file saves Aarhus municipality as a single multipolygon in a shp file.

```{r}
# load pacakges
pacman::p_load("sf", "tidyverse", "leaflet", "mapboxapi")
```

```{r}
# load data
df <- read_csv2("../data/in/kommune_grænse.csv")
```

```{r}
# Turn column into sf object
geometry <- st_as_sfc(df$shape_wkt)
# Set the current crs
st_crs(geometry) <- 25832
# Transform to leaflet/mapbox crs
geometry <- st_transform(geometry, crs = 4326)
```

```{r}
# make a new df to save data
save <- tibble(desc = "kommunegrænse")
save$geometry <- geometry
# write the file
#st_write(save, "../data/multipolygons/municipality_border/kommune_border.shp")
```

```{r}
# check that it plots correctly
load <- read_sf("../data/multipolygons/municipality_border/kommune_border.shp")

# Plot map
leaflet() %>%
  addMapboxTiles(style_id = "outdoors-v11", username = "mapbox") %>% 
  addPolygons(data = load$geometry, color = "black", weight = 2, fill = FALSE)

```

```{r}
# Plot map
leaflet() %>%
  addMapboxTiles(style_id = "outdoors-v11", username = "mapbox") %>% 
  addPolygons(data = load$geometry, 
              color = c("red"),
              fillColor = c("red"),
              fillOpacity = 1, 
              opacity = 1, 
              weight = 0.2)
  
```

